apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: fusiondirectory-gw
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 15033
      name: http-fd
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: fusiondirectory
  namespace: default
spec:
  gateways:
  - fusiondirectory-gw.istio-system
  hosts:
  - '*'
  http:
  - match:
    - port: 15033
    route:
    - destination:
        host: fusiondirectory
        port:
          number: 8080
